### ISSUE TITLE
Does not build with Inkscape >= 1.0

### ISSUE THREAD

**Issue by tinxx** [saligari/captain-frank-cursors#1]
Hey @saligari, I wanted to try your cursors but it seems like the build script does not work with my Inkscape version 1.0.

```
Unknown option -z
```

**Comment by saligari** [comment]
Uh, I haven't logged in for some time (exams). I've moved to Gnome the past couple of months so I won't be updating this probably.

edit: looked it up, -z was an option to run without gui which is now unneeded and -e has been changed to -o. Tried it with inkscape 1.01 installed and it ran ok, so I suppose it works now, yay!
